### ISSUE TITLE
How does one run this program

### ISSUE THREAD

**Issue by LittleTimmy52** [IgorTimofeev/OCIFImageConverter#11]
I use windows 10, I dont really know how to run this, I download it, but what does one do to well... use it

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/211318114-8ac49812-c6f2-4bdf-89e3-c322ace06edc.png)

**Comment by LittleTimmy52** [comment]
Where is the jar file i need to run, i only see .xml or .java, if i try to
run the .java it can't find main, or something like that

**Comment by IgorTimofeev** [comment]
https://github.com/IgorTimofeev/OCIFImageConverter/releases/

![image](https://user-images.githubusercontent.com/11760002/211600522-6a4bef61-d2f9-4d6f-b257-ae56a1de103a.png)
