### ISSUE TITLE
Every image I try says failed to read pixel data not enough memory

### ISSUE THREAD

**Issue by LittleTimmy52** [IgorTimofeev/OCIFImageConverter#12]
i converted various images of my computer, converted them, uploaded them to github then copied them to the maxed out t3 computer, but I cant open it nor can I set it to my wall paper as per the above error. I get the same with the defaule wall papers, but I can atleast set them to be my wall paper and they display fine. my ask is is there a way to compress the image or something with this converter so it can display ingame?

**Comment by IgorTimofeev** [comment]
It all depends on the size of the image, the number of its colors, as well as the "heaviness" of the software that you run in parallel. If you get "not enough memory" error when starting a "clean" OS, something is definitely wrong. 2 sticks of Tier 3.5 RAM have always been enough for me for displaying 160x50 dithered wallpaper and running simple windowed software (not 3D, of course)

> maxed out t3 computer

Are you sure you've crafted Tier 3.5 sticks, not Tier 3?

**Comment by LittleTimmy52** [comment]
I am utterly sure that their 3.5 ram and there wasn't anything else, trying
to open the default wallpaper dosent work, but it displays as a wallpaper
just fine, unlike my image which doesn't display at all. it's most likely
the thing you said about the image though. I do have a question, is there a
way to reduce it's color scale so to say? And compress it to some lower
resolution?

**Comment by IgorTimofeev** [comment]
> way to reduce it's color scale so to say? And compress it to some lower

No, there is no such way. The graphic format of images is already sufficiently optimized; during development, every byte was counted

Btw I still don't know what image did you used, so I've checked your repo and took [this one](https://github.com/LittleTimmy52/OpenComputers/blob/master/MineOS/Pictures/Fantom2.pic) as a sample. It appears to be 60 pixels tall, which is way too big for 2 sticks of RAM:

![image](https://user-images.githubusercontent.com/11760002/212086101-cf6bdbe9-c7ee-4d18-b6cb-d517b217d14b.png)

For example, all standard pictures are adjusted to the base resolution of a Tier 3 GPU of 160 x 50 pixels, which barely fits into the limit. So the only solution I see is crafting a server rack and installing 4 memory bars or reducing image height ¯\\_(ツ)_/¯

**Comment by LittleTimmy52** [comment]
Ok thanks, though i do believe I have done that with a different picture on
my repo and it not working, I needed an upgrade on my setup anyway so, I'll
do both, get a server with more ram and reduce the image height.
