### ISSUE TITLE
Does not convert transparency.

### ISSUE THREAD

**Issue by Namelessys** [IgorTimofeev/OCIFImageConverter#4]
I tried to convert PNGs containing transparency but all transparent areas are just black in the end.

Settings:
&#8195; Format: OCIF6
&#8195; Enable brialle font: false
&#8195; Enable dithering: true

Original PNG:
![truck](https://user-images.githubusercontent.com/49952271/75882427-7189a800-5e21-11ea-8ed3-d5c6e3287641.png)

Ingame result:
![truckConverResult](https://user-images.githubusercontent.com/49952271/75882549-ae559f00-5e21-11ea-992d-db5684d7fe40.PNG)

Zoomed out ingame result:
![truckZoomedOut](https://user-images.githubusercontent.com/49952271/75883151-d1cd1980-5e22-11ea-895f-c953f038b064.PNG)

**Comment by IgorTimofeev** [comment]
Transparency isn't supported by converter - and never will be cause lots of artifacts. Converter was designed for BIG images without alpha channel. For such detailed .pic editing you can use PictureEdit and it's Braille Tool from MineOS. For OpenOS there's nothing I can help you with

**Comment by Namelessys** [comment]
Too bad but no big deal. I have worked a way around this limitation using a LUA function making a specific color of a loaded pic transparent. The function probably causing issues with braille font or other formats as OCIF6 (haven't tested it), but it is working fine for my purpose.

LUA function:
```lua
return function(image, color) 
	for i = 1, #image[3] do
		if image[3][i] == color and image[4][i] == color then
			image[5][i] = 2
		elseif image[3][i] == color then
			image[5][i] = 1
		elseif image[4][i] == color then
			local bc, fc = image[3][i], image[4][i]
			image[3][i], image[4][i] = fc, bc
			image[6][i] = "▀"
			image[5][i] = 1
		end
	end
end
```

**Comment by arduinka55055** [comment]
Yes, i have the same problem with drawing small icons where transparency is important. 
But picture edit isnt best solution for some difficult icons.
