### ISSUE TITLE
[Question / Suggestion] CLI tool

### ISSUE THREAD

**Issue by Namelessys** [IgorTimofeev/OCIFImageConverter#9]
Is it possible to use this converter using a command line interface?

This would be really helpful to get a fluid work flow in combination with some shell scripts.
Especially with bigger projects where you have to convert multiple textures, all over again.

**Comment by IgorTimofeev** [comment]
No, it's not possible for now. Maybe someone will do it xd

**Comment by Namelessys** [comment]
I made a CLI version of the tool. 
Its quite slow due to my missing java skills, but it lets you convert a whole folder full of images by running a single command.

https://github.com/NosPo-Studio/OCIFImageConverterCLI

**Comment by IgorTimofeev** [comment]
@MisterNoNameLP nice job, thank you ❤️
